### ISSUE TITLE
Filter files to be embeded.

### ISSUE THREAD

**Issue by AidasK** [ehynds/grunt-image-embed#18]
I have an issue with less to css compiler, because i can't use "/_ImageEmbed:skip_/" comment. It is striped off after minification.

``` less
@font-face {
  font-family: 'BebasNeueRegular';
  src: url('../font/BebasNeue-webfont.eot');
  src: url('../font/BebasNeue-webfont_2d2816fe.eot#iefix') format('embedded-opentype'),url('../font/BebasNeue-webfont.woff') format('woff'),url('../font/BebasNeue-webfont.ttf') format('truetype'),url('../font/BebasNeue-webfont.svg#BebasNeueRegular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

I would like to have an option to prevent fonts embeding, or option to filter files.
This would be very useful for less users.

Thanks.
