### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by monolithed** [ehynds/grunt-image-embed#39]
```
Running "imageEmbed:toolbar" (imageEmbed) task
Warning: File /node_modules/grunt-image-embed/tasks/lib/img.imgsmail.ru/r/default/fonts/sept.503.eot does not exist Use --force to continue.
```

``` css
.foo {
    font-family :'sept';
    src: url("//img.imgsmail.ru/r/default/fonts/sept.503.eot");
}
```

Why do you parse the strings started with **//**?
